/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgrammeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Programme");
		private final Assignment cLoadscopesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLoadscopesLoadscopeParserRuleCall_0 = (RuleCall)cLoadscopesAssignment.eContents().get(0);
		
		//Programme:
		//    loadscopes+=Loadscope*;
		@Override public ParserRule getRule() { return rule; }
		
		//loadscopes+=Loadscope*
		public Assignment getLoadscopesAssignment() { return cLoadscopesAssignment; }
		
		//Loadscope
		public RuleCall getLoadscopesLoadscopeParserRuleCall_0() { return cLoadscopesLoadscopeParserRuleCall_0; }
	}
	public class LoadscopeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Loadscope");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLoadParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCreateParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Loadscope :
		//    Load | Create
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Load | Create
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Load
		public RuleCall getLoadParserRuleCall_0() { return cLoadParserRuleCall_0; }
		
		//Create
		public RuleCall getCreateParserRuleCall_1() { return cCreateParserRuleCall_1; }
	}
	public class LoadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Load");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoadKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPathAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPathSTRINGTerminalRuleCall_1_0 = (RuleCall)cPathAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cInstructionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cInstructionsInstructionParserRuleCall_4_0 = (RuleCall)cInstructionsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Load :
		//    'Load(' path=STRING ')' '{' instructions+=Instruction* '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Load(' path=STRING ')' '{' instructions+=Instruction* '}'
		public Group getGroup() { return cGroup; }
		
		//'Load('
		public Keyword getLoadKeyword_0() { return cLoadKeyword_0; }
		
		//path=STRING
		public Assignment getPathAssignment_1() { return cPathAssignment_1; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_1_0() { return cPathSTRINGTerminalRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//instructions+=Instruction*
		public Assignment getInstructionsAssignment_4() { return cInstructionsAssignment_4; }
		
		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_4_0() { return cInstructionsInstructionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class CreateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Create");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCreateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInstructionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInstructionsInstructionParserRuleCall_2_0 = (RuleCall)cInstructionsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Create :
		//    'Create()' '{' instructions+=Instruction* '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Create()' '{' instructions+=Instruction* '}'
		public Group getGroup() { return cGroup; }
		
		//'Create()'
		public Keyword getCreateKeyword_0() { return cCreateKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//instructions+=Instruction*
		public Assignment getInstructionsAssignment_2() { return cInstructionsAssignment_2; }
		
		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_2_0() { return cInstructionsInstructionParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Instruction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cInsertLineParserRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cRemoveLineParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final RuleCall cInsertColParserRuleCall_0_2 = (RuleCall)cAlternatives_0.eContents().get(2);
		private final RuleCall cRemoveColParserRuleCall_0_3 = (RuleCall)cAlternatives_0.eContents().get(3);
		private final RuleCall cInsertParserRuleCall_0_4 = (RuleCall)cAlternatives_0.eContents().get(4);
		private final RuleCall cExportJSONParserRuleCall_0_5 = (RuleCall)cAlternatives_0.eContents().get(5);
		private final RuleCall cExportCSVParserRuleCall_0_6 = (RuleCall)cAlternatives_0.eContents().get(6);
		private final RuleCall cPrintParserRuleCall_0_7 = (RuleCall)cAlternatives_0.eContents().get(7);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Instruction :
		//     ( InsertLine | RemoveLine | InsertCol | RemoveCol | Insert | ExportJSON | ExportCSV | Print) ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//( InsertLine | RemoveLine | InsertCol | RemoveCol | Insert | ExportJSON | ExportCSV | Print) ';'
		public Group getGroup() { return cGroup; }
		
		//( InsertLine | RemoveLine | InsertCol | RemoveCol | Insert | ExportJSON | ExportCSV | Print)
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//InsertLine
		public RuleCall getInsertLineParserRuleCall_0_0() { return cInsertLineParserRuleCall_0_0; }
		
		//RemoveLine
		public RuleCall getRemoveLineParserRuleCall_0_1() { return cRemoveLineParserRuleCall_0_1; }
		
		//InsertCol
		public RuleCall getInsertColParserRuleCall_0_2() { return cInsertColParserRuleCall_0_2; }
		
		//RemoveCol
		public RuleCall getRemoveColParserRuleCall_0_3() { return cRemoveColParserRuleCall_0_3; }
		
		//Insert
		public RuleCall getInsertParserRuleCall_0_4() { return cInsertParserRuleCall_0_4; }
		
		//ExportJSON
		public RuleCall getExportJSONParserRuleCall_0_5() { return cExportJSONParserRuleCall_0_5; }
		
		//ExportCSV
		public RuleCall getExportCSVParserRuleCall_0_6() { return cExportCSVParserRuleCall_0_6; }
		
		//Print
		public RuleCall getPrintParserRuleCall_0_7() { return cPrintParserRuleCall_0_7; }
		
		//';'
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}
	public class InsertColElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.InsertCol");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInsertColKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cColIndexAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cColIndexExpressionParserRuleCall_1_0 = (RuleCall)cColIndexAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cColNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cColNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cExpAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cExpExpressionParserRuleCall_4_1_0 = (RuleCall)cExpAssignment_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//InsertCol : //insert col at INT with name STRING
		//    'InsertCol(' colIndex=Expression ',' colName=STRING (','exp=Expression)?')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////insert col at INT with name STRING
		//   'InsertCol(' colIndex=Expression ',' colName=STRING (','exp=Expression)?')'
		public Group getGroup() { return cGroup; }
		
		////insert col at INT with name STRING
		//   'InsertCol('
		public Keyword getInsertColKeyword_0() { return cInsertColKeyword_0; }
		
		//colIndex=Expression
		public Assignment getColIndexAssignment_1() { return cColIndexAssignment_1; }
		
		//Expression
		public RuleCall getColIndexExpressionParserRuleCall_1_0() { return cColIndexExpressionParserRuleCall_1_0; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//colName=STRING
		public Assignment getColNameAssignment_3() { return cColNameAssignment_3; }
		
		//STRING
		public RuleCall getColNameSTRINGTerminalRuleCall_3_0() { return cColNameSTRINGTerminalRuleCall_3_0; }
		
		//(','exp=Expression)?
		public Group getGroup_4() { return cGroup_4; }
		
		//','
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//exp=Expression
		public Assignment getExpAssignment_4_1() { return cExpAssignment_4_1; }
		
		//Expression
		public RuleCall getExpExpressionParserRuleCall_4_1_0() { return cExpExpressionParserRuleCall_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class RemoveColElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RemoveCol");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cRemoveColKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cColIndexAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cColIndexExpressionParserRuleCall_0_1_0 = (RuleCall)cColIndexAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cNameAssignment_1_0.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//RemoveCol :
		//    'RemoveCol(' colIndex=Expression | name=STRING')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'RemoveCol(' colIndex=Expression | name=STRING')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'RemoveCol(' colIndex=Expression
		public Group getGroup_0() { return cGroup_0; }
		
		//'RemoveCol('
		public Keyword getRemoveColKeyword_0_0() { return cRemoveColKeyword_0_0; }
		
		//colIndex=Expression
		public Assignment getColIndexAssignment_0_1() { return cColIndexAssignment_0_1; }
		
		//Expression
		public RuleCall getColIndexExpressionParserRuleCall_0_1_0() { return cColIndexExpressionParserRuleCall_0_1_0; }
		
		//name=STRING')'
		public Group getGroup_1() { return cGroup_1; }
		
		//name=STRING
		public Assignment getNameAssignment_1_0() { return cNameAssignment_1_0; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0_0() { return cNameSTRINGTerminalRuleCall_1_0_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_1() { return cRightParenthesisKeyword_1_1; }
	}
	public class InsertLineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.InsertLine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInsertLineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLineIndexAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLineIndexExpressionParserRuleCall_1_0 = (RuleCall)cLineIndexAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cExpsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cExpsExpressionParserRuleCall_2_1_0 = (RuleCall)cExpsAssignment_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//InsertLine : //insert line at INT
		//    'InsertLine(' lineIndex=Expression (','exps+=Expression )+ ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////insert line at INT
		//   'InsertLine(' lineIndex=Expression (','exps+=Expression )+ ')'
		public Group getGroup() { return cGroup; }
		
		////insert line at INT
		//   'InsertLine('
		public Keyword getInsertLineKeyword_0() { return cInsertLineKeyword_0; }
		
		//lineIndex=Expression
		public Assignment getLineIndexAssignment_1() { return cLineIndexAssignment_1; }
		
		//Expression
		public RuleCall getLineIndexExpressionParserRuleCall_1_0() { return cLineIndexExpressionParserRuleCall_1_0; }
		
		//(','exps+=Expression )+
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//exps+=Expression
		public Assignment getExpsAssignment_2_1() { return cExpsAssignment_2_1; }
		
		//Expression
		public RuleCall getExpsExpressionParserRuleCall_2_1_0() { return cExpsExpressionParserRuleCall_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class RemoveLineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RemoveLine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRemoveLineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLineIndexAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLineIndexExpressionParserRuleCall_1_0 = (RuleCall)cLineIndexAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//RemoveLine :
		//    'RemoveLine(' lineIndex=Expression ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'RemoveLine(' lineIndex=Expression ')'
		public Group getGroup() { return cGroup; }
		
		//'RemoveLine('
		public Keyword getRemoveLineKeyword_0() { return cRemoveLineKeyword_0; }
		
		//lineIndex=Expression
		public Assignment getLineIndexAssignment_1() { return cLineIndexAssignment_1; }
		
		//Expression
		public RuleCall getLineIndexExpressionParserRuleCall_1_0() { return cLineIndexExpressionParserRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class InsertElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Insert");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInsertKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLineIndexAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLineIndexExpressionParserRuleCall_1_0 = (RuleCall)cLineIndexAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColNameOrIndexAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cColNameOrIndexExpressionParserRuleCall_3_0 = (RuleCall)cColNameOrIndexAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Alternatives cValueAlternatives_5_0 = (Alternatives)cValueAssignment_5.eContents().get(0);
		private final RuleCall cValueExpressionParserRuleCall_5_0_0 = (RuleCall)cValueAlternatives_5_0.eContents().get(0);
		private final RuleCall cValueStringValueParserRuleCall_5_0_1 = (RuleCall)cValueAlternatives_5_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Insert : // Looks like a modify but is translated as an update in python
		//    'Insert(' lineIndex=Expression ',' colNameOrIndex=Expression ',' value=(Expression | StringValue) ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//// Looks like a modify but is translated as an update in python
		//   'Insert(' lineIndex=Expression ',' colNameOrIndex=Expression ',' value=(Expression | StringValue) ')'
		public Group getGroup() { return cGroup; }
		
		//// Looks like a modify but is translated as an update in python
		//   'Insert('
		public Keyword getInsertKeyword_0() { return cInsertKeyword_0; }
		
		//lineIndex=Expression
		public Assignment getLineIndexAssignment_1() { return cLineIndexAssignment_1; }
		
		//Expression
		public RuleCall getLineIndexExpressionParserRuleCall_1_0() { return cLineIndexExpressionParserRuleCall_1_0; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//colNameOrIndex=Expression
		public Assignment getColNameOrIndexAssignment_3() { return cColNameOrIndexAssignment_3; }
		
		//Expression
		public RuleCall getColNameOrIndexExpressionParserRuleCall_3_0() { return cColNameOrIndexExpressionParserRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//value=(Expression | StringValue)
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//(Expression | StringValue)
		public Alternatives getValueAlternatives_5_0() { return cValueAlternatives_5_0; }
		
		//Expression
		public RuleCall getValueExpressionParserRuleCall_5_0_0() { return cValueExpressionParserRuleCall_5_0_0; }
		
		//StringValue
		public RuleCall getValueStringValueParserRuleCall_5_0_1() { return cValueStringValueParserRuleCall_5_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	public class PrintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Print");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrintKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cValueAlternatives_1_0 = (Alternatives)cValueAssignment_1.eContents().get(0);
		private final RuleCall cValueExpressionParserRuleCall_1_0_0 = (RuleCall)cValueAlternatives_1_0.eContents().get(0);
		private final RuleCall cValueStringValueParserRuleCall_1_0_1 = (RuleCall)cValueAlternatives_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Print :
		//    'Print('value=(Expression|StringValue)')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Print('value=(Expression|StringValue)')'
		public Group getGroup() { return cGroup; }
		
		//'Print('
		public Keyword getPrintKeyword_0() { return cPrintKeyword_0; }
		
		//value=(Expression|StringValue)
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//(Expression|StringValue)
		public Alternatives getValueAlternatives_1_0() { return cValueAlternatives_1_0; }
		
		//Expression
		public RuleCall getValueExpressionParserRuleCall_1_0_0() { return cValueExpressionParserRuleCall_1_0_0; }
		
		//StringValue
		public RuleCall getValueStringValueParserRuleCall_1_0_1() { return cValueStringValueParserRuleCall_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class ExportCSVElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ExportCSV");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStoreKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPathAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPathSTRINGTerminalRuleCall_1_0 = (RuleCall)cPathAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ExportCSV :
		//    'Store('path=STRING')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Store('path=STRING')'
		public Group getGroup() { return cGroup; }
		
		//'Store('
		public Keyword getStoreKeyword_0() { return cStoreKeyword_0; }
		
		//path=STRING
		public Assignment getPathAssignment_1() { return cPathAssignment_1; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_1_0() { return cPathSTRINGTerminalRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class ExportJSONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ExportJSON");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPathAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPathSTRINGTerminalRuleCall_1_0 = (RuleCall)cPathAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ExportJSON :
		//    'Export('path=STRING')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Export('path=STRING')'
		public Group getGroup() { return cGroup; }
		
		//'Export('
		public Keyword getExportKeyword_0() { return cExportKeyword_0; }
		
		//path=STRING
		public Assignment getPathAssignment_1() { return cPathAssignment_1; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_1_0() { return cPathSTRINGTerminalRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPrimaryExpressionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBinexprParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNoneValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Expression :
		//    (PrimaryExpression | Binexpr | NoneValue)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(PrimaryExpression | Binexpr | NoneValue)
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_0() { return cPrimaryExpressionParserRuleCall_0; }
		
		//Binexpr
		public RuleCall getBinexprParserRuleCall_1() { return cBinexprParserRuleCall_1; }
		
		//NoneValue
		public RuleCall getNoneValueParserRuleCall_2() { return cNoneValueParserRuleCall_2; }
	}
	public class PrimaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.PrimaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSelectcellParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLinesumParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cColsumParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cLineprodParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cColprodParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//PrimaryExpression :
		//    (IntValue | Selectcell | Linesum | Colsum | Lineprod | Colprod)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(IntValue | Selectcell | Linesum | Colsum | Lineprod | Colprod)
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntValue
		public RuleCall getIntValueParserRuleCall_0() { return cIntValueParserRuleCall_0; }
		
		//Selectcell
		public RuleCall getSelectcellParserRuleCall_1() { return cSelectcellParserRuleCall_1; }
		
		//Linesum
		public RuleCall getLinesumParserRuleCall_2() { return cLinesumParserRuleCall_2; }
		
		//Colsum
		public RuleCall getColsumParserRuleCall_3() { return cColsumParserRuleCall_3; }
		
		//Lineprod
		public RuleCall getLineprodParserRuleCall_4() { return cLineprodParserRuleCall_4; }
		
		//Colprod
		public RuleCall getColprodParserRuleCall_5() { return cColprodParserRuleCall_5; }
	}
	public class SelectcellElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Selectcell");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectcellKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCellXAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCellXExpressionParserRuleCall_1_0 = (RuleCall)cCellXAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCellYAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCellYExpressionParserRuleCall_3_0 = (RuleCall)cCellYAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Selectcell :
		//    'Selectcell('cellX=Expression','cellY=Expression')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Selectcell('cellX=Expression','cellY=Expression')'
		public Group getGroup() { return cGroup; }
		
		//'Selectcell('
		public Keyword getSelectcellKeyword_0() { return cSelectcellKeyword_0; }
		
		//cellX=Expression
		public Assignment getCellXAssignment_1() { return cCellXAssignment_1; }
		
		//Expression
		public RuleCall getCellXExpressionParserRuleCall_1_0() { return cCellXExpressionParserRuleCall_1_0; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//cellY=Expression
		public Assignment getCellYAssignment_3() { return cCellYAssignment_3; }
		
		//Expression
		public RuleCall getCellYExpressionParserRuleCall_3_0() { return cCellYExpressionParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class LinesumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Linesum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLinesumKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLineIndexAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLineIndexExpressionParserRuleCall_1_0 = (RuleCall)cLineIndexAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Linesum: //somme de toutes les case de la ligne INT
		//    'Linesum('lineIndex=Expression')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////somme de toutes les case de la ligne INT
		//   'Linesum('lineIndex=Expression')'
		public Group getGroup() { return cGroup; }
		
		////somme de toutes les case de la ligne INT
		//   'Linesum('
		public Keyword getLinesumKeyword_0() { return cLinesumKeyword_0; }
		
		//lineIndex=Expression
		public Assignment getLineIndexAssignment_1() { return cLineIndexAssignment_1; }
		
		//Expression
		public RuleCall getLineIndexExpressionParserRuleCall_1_0() { return cLineIndexExpressionParserRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class ColsumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Colsum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cColsumKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cColIndexAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cColIndexExpressionParserRuleCall_0_1_0 = (RuleCall)cColIndexAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cNameAssignment_1_0.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//Colsum : //somme de toutes les case de la col INT
		//    'Colsum('colIndex=Expression | name=STRING')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////somme de toutes les case de la col INT
		//   'Colsum('colIndex=Expression | name=STRING')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		////somme de toutes les case de la col INT
		//   'Colsum('colIndex=Expression
		public Group getGroup_0() { return cGroup_0; }
		
		////somme de toutes les case de la col INT
		//   'Colsum('
		public Keyword getColsumKeyword_0_0() { return cColsumKeyword_0_0; }
		
		//colIndex=Expression
		public Assignment getColIndexAssignment_0_1() { return cColIndexAssignment_0_1; }
		
		//Expression
		public RuleCall getColIndexExpressionParserRuleCall_0_1_0() { return cColIndexExpressionParserRuleCall_0_1_0; }
		
		//name=STRING')'
		public Group getGroup_1() { return cGroup_1; }
		
		//name=STRING
		public Assignment getNameAssignment_1_0() { return cNameAssignment_1_0; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0_0() { return cNameSTRINGTerminalRuleCall_1_0_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_1() { return cRightParenthesisKeyword_1_1; }
	}
	public class LineprodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Lineprod");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLineprodKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLineIndexAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLineIndexExpressionParserRuleCall_1_0 = (RuleCall)cLineIndexAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Lineprod : //produit de toutes les case de la ligne INT
		//    'Lineprod('lineIndex=Expression')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////produit de toutes les case de la ligne INT
		//   'Lineprod('lineIndex=Expression')'
		public Group getGroup() { return cGroup; }
		
		////produit de toutes les case de la ligne INT
		//   'Lineprod('
		public Keyword getLineprodKeyword_0() { return cLineprodKeyword_0; }
		
		//lineIndex=Expression
		public Assignment getLineIndexAssignment_1() { return cLineIndexAssignment_1; }
		
		//Expression
		public RuleCall getLineIndexExpressionParserRuleCall_1_0() { return cLineIndexExpressionParserRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class ColprodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Colprod");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cColprodKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cColIndexAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cColIndexExpressionParserRuleCall_0_1_0 = (RuleCall)cColIndexAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0_0 = (RuleCall)cNameAssignment_1_0.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//Colprod : //produit de toutes les case de la col INT
		//    'Colprod('colIndex=Expression | name=STRING ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		////produit de toutes les case de la col INT
		//   'Colprod('colIndex=Expression | name=STRING ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		////produit de toutes les case de la col INT
		//   'Colprod('colIndex=Expression
		public Group getGroup_0() { return cGroup_0; }
		
		////produit de toutes les case de la col INT
		//   'Colprod('
		public Keyword getColprodKeyword_0_0() { return cColprodKeyword_0_0; }
		
		//colIndex=Expression
		public Assignment getColIndexAssignment_0_1() { return cColIndexAssignment_0_1; }
		
		//Expression
		public RuleCall getColIndexExpressionParserRuleCall_0_1_0() { return cColIndexExpressionParserRuleCall_0_1_0; }
		
		//name=STRING ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//name=STRING
		public Assignment getNameAssignment_1_0() { return cNameAssignment_1_0; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0_0() { return cNameSTRINGTerminalRuleCall_1_0_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_1() { return cRightParenthesisKeyword_1_1; }
	}
	public class BinexprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Binexpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLeftAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLeftPrimaryExpressionParserRuleCall_1_0 = (RuleCall)cLeftAssignment_1.eContents().get(0);
		private final Assignment cOpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOpOpParserRuleCall_2_0 = (RuleCall)cOpAssignment_2.eContents().get(0);
		private final Assignment cRightAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRightExpressionParserRuleCall_3_0 = (RuleCall)cRightAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Binexpr :
		//    '(' left=PrimaryExpression op=Op right=Expression ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'(' left=PrimaryExpression op=Op right=Expression ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//left=PrimaryExpression
		public Assignment getLeftAssignment_1() { return cLeftAssignment_1; }
		
		//PrimaryExpression
		public RuleCall getLeftPrimaryExpressionParserRuleCall_1_0() { return cLeftPrimaryExpressionParserRuleCall_1_0; }
		
		//op=Op
		public Assignment getOpAssignment_2() { return cOpAssignment_2; }
		
		//Op
		public RuleCall getOpOpParserRuleCall_2_0() { return cOpOpParserRuleCall_2_0; }
		
		//right=Expression
		public Assignment getRightAssignment_3() { return cRightAssignment_3; }
		
		//Expression
		public RuleCall getRightExpressionParserRuleCall_3_0() { return cRightExpressionParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class OpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Op");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cAsteriskKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cSolidusKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//Op :
		//    '+' | '-' | '*' | '/'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'+' | '-' | '*' | '/'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'+'
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//'*'
		public Keyword getAsteriskKeyword_2() { return cAsteriskKeyword_2; }
		
		//'/'
		public Keyword getSolidusKeyword_3() { return cSolidusKeyword_3; }
	}
	public class NoneValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.NoneValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueNoneKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//NoneValue :
		//    value="None"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value="None"
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//"None"
		public Keyword getValueNoneKeyword_0() { return cValueNoneKeyword_0; }
	}
	public class IntValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.IntValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntValue :
		//    value=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}
	public class StringValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.StringValue");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//StringValue :
		//    value=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}
	
	
	private final ProgrammeElements pProgramme;
	private final LoadscopeElements pLoadscope;
	private final LoadElements pLoad;
	private final CreateElements pCreate;
	private final InstructionElements pInstruction;
	private final InsertColElements pInsertCol;
	private final RemoveColElements pRemoveCol;
	private final InsertLineElements pInsertLine;
	private final RemoveLineElements pRemoveLine;
	private final InsertElements pInsert;
	private final PrintElements pPrint;
	private final ExportCSVElements pExportCSV;
	private final ExportJSONElements pExportJSON;
	private final ExpressionElements pExpression;
	private final PrimaryExpressionElements pPrimaryExpression;
	private final SelectcellElements pSelectcell;
	private final LinesumElements pLinesum;
	private final ColsumElements pColsum;
	private final LineprodElements pLineprod;
	private final ColprodElements pColprod;
	private final BinexprElements pBinexpr;
	private final OpElements pOp;
	private final NoneValueElements pNoneValue;
	private final IntValueElements pIntValue;
	private final StringValueElements pStringValue;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgramme = new ProgrammeElements();
		this.pLoadscope = new LoadscopeElements();
		this.pLoad = new LoadElements();
		this.pCreate = new CreateElements();
		this.pInstruction = new InstructionElements();
		this.pInsertCol = new InsertColElements();
		this.pRemoveCol = new RemoveColElements();
		this.pInsertLine = new InsertLineElements();
		this.pRemoveLine = new RemoveLineElements();
		this.pInsert = new InsertElements();
		this.pPrint = new PrintElements();
		this.pExportCSV = new ExportCSVElements();
		this.pExportJSON = new ExportJSONElements();
		this.pExpression = new ExpressionElements();
		this.pPrimaryExpression = new PrimaryExpressionElements();
		this.pSelectcell = new SelectcellElements();
		this.pLinesum = new LinesumElements();
		this.pColsum = new ColsumElements();
		this.pLineprod = new LineprodElements();
		this.pColprod = new ColprodElements();
		this.pBinexpr = new BinexprElements();
		this.pOp = new OpElements();
		this.pNoneValue = new NoneValueElements();
		this.pIntValue = new IntValueElements();
		this.pStringValue = new StringValueElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Programme:
	//    loadscopes+=Loadscope*;
	public ProgrammeElements getProgrammeAccess() {
		return pProgramme;
	}
	
	public ParserRule getProgrammeRule() {
		return getProgrammeAccess().getRule();
	}
	
	//Loadscope :
	//    Load | Create
	//;
	public LoadscopeElements getLoadscopeAccess() {
		return pLoadscope;
	}
	
	public ParserRule getLoadscopeRule() {
		return getLoadscopeAccess().getRule();
	}
	
	//Load :
	//    'Load(' path=STRING ')' '{' instructions+=Instruction* '}'
	//;
	public LoadElements getLoadAccess() {
		return pLoad;
	}
	
	public ParserRule getLoadRule() {
		return getLoadAccess().getRule();
	}
	
	//Create :
	//    'Create()' '{' instructions+=Instruction* '}'
	//;
	public CreateElements getCreateAccess() {
		return pCreate;
	}
	
	public ParserRule getCreateRule() {
		return getCreateAccess().getRule();
	}
	
	//Instruction :
	//     ( InsertLine | RemoveLine | InsertCol | RemoveCol | Insert | ExportJSON | ExportCSV | Print) ';'
	//;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//InsertCol : //insert col at INT with name STRING
	//    'InsertCol(' colIndex=Expression ',' colName=STRING (','exp=Expression)?')'
	//;
	public InsertColElements getInsertColAccess() {
		return pInsertCol;
	}
	
	public ParserRule getInsertColRule() {
		return getInsertColAccess().getRule();
	}
	
	//RemoveCol :
	//    'RemoveCol(' colIndex=Expression | name=STRING')'
	//;
	public RemoveColElements getRemoveColAccess() {
		return pRemoveCol;
	}
	
	public ParserRule getRemoveColRule() {
		return getRemoveColAccess().getRule();
	}
	
	//InsertLine : //insert line at INT
	//    'InsertLine(' lineIndex=Expression (','exps+=Expression )+ ')'
	//;
	public InsertLineElements getInsertLineAccess() {
		return pInsertLine;
	}
	
	public ParserRule getInsertLineRule() {
		return getInsertLineAccess().getRule();
	}
	
	//RemoveLine :
	//    'RemoveLine(' lineIndex=Expression ')'
	//;
	public RemoveLineElements getRemoveLineAccess() {
		return pRemoveLine;
	}
	
	public ParserRule getRemoveLineRule() {
		return getRemoveLineAccess().getRule();
	}
	
	//Insert : // Looks like a modify but is translated as an update in python
	//    'Insert(' lineIndex=Expression ',' colNameOrIndex=Expression ',' value=(Expression | StringValue) ')'
	//;
	public InsertElements getInsertAccess() {
		return pInsert;
	}
	
	public ParserRule getInsertRule() {
		return getInsertAccess().getRule();
	}
	
	//Print :
	//    'Print('value=(Expression|StringValue)')'
	//;
	public PrintElements getPrintAccess() {
		return pPrint;
	}
	
	public ParserRule getPrintRule() {
		return getPrintAccess().getRule();
	}
	
	//ExportCSV :
	//    'Store('path=STRING')'
	//;
	public ExportCSVElements getExportCSVAccess() {
		return pExportCSV;
	}
	
	public ParserRule getExportCSVRule() {
		return getExportCSVAccess().getRule();
	}
	
	//ExportJSON :
	//    'Export('path=STRING')'
	//;
	public ExportJSONElements getExportJSONAccess() {
		return pExportJSON;
	}
	
	public ParserRule getExportJSONRule() {
		return getExportJSONAccess().getRule();
	}
	
	//Expression :
	//    (PrimaryExpression | Binexpr | NoneValue)
	//;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//PrimaryExpression :
	//    (IntValue | Selectcell | Linesum | Colsum | Lineprod | Colprod)
	//;
	public PrimaryExpressionElements getPrimaryExpressionAccess() {
		return pPrimaryExpression;
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}
	
	//Selectcell :
	//    'Selectcell('cellX=Expression','cellY=Expression')'
	//;
	public SelectcellElements getSelectcellAccess() {
		return pSelectcell;
	}
	
	public ParserRule getSelectcellRule() {
		return getSelectcellAccess().getRule();
	}
	
	//Linesum: //somme de toutes les case de la ligne INT
	//    'Linesum('lineIndex=Expression')'
	//;
	public LinesumElements getLinesumAccess() {
		return pLinesum;
	}
	
	public ParserRule getLinesumRule() {
		return getLinesumAccess().getRule();
	}
	
	//Colsum : //somme de toutes les case de la col INT
	//    'Colsum('colIndex=Expression | name=STRING')'
	//;
	public ColsumElements getColsumAccess() {
		return pColsum;
	}
	
	public ParserRule getColsumRule() {
		return getColsumAccess().getRule();
	}
	
	//Lineprod : //produit de toutes les case de la ligne INT
	//    'Lineprod('lineIndex=Expression')'
	//;
	public LineprodElements getLineprodAccess() {
		return pLineprod;
	}
	
	public ParserRule getLineprodRule() {
		return getLineprodAccess().getRule();
	}
	
	//Colprod : //produit de toutes les case de la col INT
	//    'Colprod('colIndex=Expression | name=STRING ')'
	//;
	public ColprodElements getColprodAccess() {
		return pColprod;
	}
	
	public ParserRule getColprodRule() {
		return getColprodAccess().getRule();
	}
	
	//Binexpr :
	//    '(' left=PrimaryExpression op=Op right=Expression ')'
	//;
	public BinexprElements getBinexprAccess() {
		return pBinexpr;
	}
	
	public ParserRule getBinexprRule() {
		return getBinexprAccess().getRule();
	}
	
	//Op :
	//    '+' | '-' | '*' | '/'
	//;
	public OpElements getOpAccess() {
		return pOp;
	}
	
	public ParserRule getOpRule() {
		return getOpAccess().getRule();
	}
	
	//NoneValue :
	//    value="None"
	//;
	public NoneValueElements getNoneValueAccess() {
		return pNoneValue;
	}
	
	public ParserRule getNoneValueRule() {
		return getNoneValueAccess().getRule();
	}
	
	//IntValue :
	//    value=INT
	//;
	public IntValueElements getIntValueAccess() {
		return pIntValue;
	}
	
	public ParserRule getIntValueRule() {
		return getIntValueAccess().getRule();
	}
	
	//StringValue :
	//    value=STRING
	//;
	public StringValueElements getStringValueAccess() {
		return pStringValue;
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
