/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.BinaryExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.BinaryExpression#getOp <em>Op</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.BinaryExpression#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getBinaryExpression()
 * @model
 * @generated
 */
public interface BinaryExpression extends Expression, MathExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(MathPrimaryExpression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getBinaryExpression_Left()
   * @model containment="true"
   * @generated
   */
  MathPrimaryExpression getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.BinaryExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(MathPrimaryExpression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getBinaryExpression_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.BinaryExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(MathExpression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getBinaryExpression_Right()
   * @model containment="true"
   * @generated
   */
  MathExpression getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.BinaryExpression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(MathExpression value);

} // BinaryExpression
