/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.idmdsl.IdmdslFactory
 * @model kind="package"
 * @generated
 */
public interface IdmdslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "idmdsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "idmdsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IdmdslPackage eINSTANCE = org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ProgrammeImpl <em>Programme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ProgrammeImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getProgramme()
   * @generated
   */
  int PROGRAMME = 0;

  /**
   * The feature id for the '<em><b>Loadscopes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME__LOADSCOPES = 0;

  /**
   * The number of structural features of the '<em>Programme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.LoadscopeImpl <em>Loadscope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.LoadscopeImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLoadscope()
   * @generated
   */
  int LOADSCOPE = 1;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOADSCOPE__URL = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOADSCOPE__INSTRUCTIONS = 1;

  /**
   * The number of structural features of the '<em>Loadscope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOADSCOPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.InstructionImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 2;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertColImpl <em>Insert Col</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.InsertColImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsertCol()
   * @generated
   */
  int INSERT_COL = 3;

  /**
   * The feature id for the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_COL__COL_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Col Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_COL__COL_NAME = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Insert Col</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_COL_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.RemoveColImpl <em>Remove Col</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.RemoveColImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getRemoveCol()
   * @generated
   */
  int REMOVE_COL = 4;

  /**
   * The feature id for the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_COL__COL_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Remove Col</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_COL_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertLineImpl <em>Insert Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.InsertLineImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsertLine()
   * @generated
   */
  int INSERT_LINE = 5;

  /**
   * The feature id for the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_LINE__LINE_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Insert Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_LINE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.RemoveLineImpl <em>Remove Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.RemoveLineImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getRemoveLine()
   * @generated
   */
  int REMOVE_LINE = 6;

  /**
   * The feature id for the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_LINE__LINE_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Remove Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_LINE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ModifyImpl <em>Modify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ModifyImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getModify()
   * @generated
   */
  int MODIFY = 7;

  /**
   * The feature id for the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY__COL_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Row Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY__ROW_INDEX = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY__VALUE = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Modify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFY_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.PrintImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.StoreImpl <em>Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.StoreImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getStore()
   * @generated
   */
  int STORE = 9;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE__URL = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExportImpl <em>Export</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ExportImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExport()
   * @generated
   */
  int EXPORT = 10;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT__URL = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Export</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ExpressionImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__VALUE = 0;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.PrimaryExpressionImpl <em>Primary Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.PrimaryExpressionImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getPrimaryExpression()
   * @generated
   */
  int PRIMARY_EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION__VALUE = 0;

  /**
   * The number of structural features of the '<em>Primary Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl <em>Selectcell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getSelectcell()
   * @generated
   */
  int SELECTCELL = 13;

  /**
   * The feature id for the '<em><b>Cell X</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTCELL__CELL_X = 0;

  /**
   * The feature id for the '<em><b>Cell Y</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTCELL__CELL_Y = 1;

  /**
   * The number of structural features of the '<em>Selectcell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTCELL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.LinesumImpl <em>Linesum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.LinesumImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLinesum()
   * @generated
   */
  int LINESUM = 14;

  /**
   * The feature id for the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINESUM__LINE_INDEX = 0;

  /**
   * The number of structural features of the '<em>Linesum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINESUM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ColsumImpl <em>Colsum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ColsumImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getColsum()
   * @generated
   */
  int COLSUM = 15;

  /**
   * The feature id for the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLSUM__COL_INDEX = 0;

  /**
   * The number of structural features of the '<em>Colsum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLSUM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.LineprodImpl <em>Lineprod</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.LineprodImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLineprod()
   * @generated
   */
  int LINEPROD = 16;

  /**
   * The feature id for the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEPROD__LINE_INDEX = 0;

  /**
   * The number of structural features of the '<em>Lineprod</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEPROD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ColprodImpl <em>Colprod</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ColprodImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getColprod()
   * @generated
   */
  int COLPROD = 17;

  /**
   * The feature id for the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLPROD__COL_INDEX = 0;

  /**
   * The number of structural features of the '<em>Colprod</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLPROD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.BinexprImpl <em>Binexpr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.BinexprImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getBinexpr()
   * @generated
   */
  int BINEXPR = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINEXPR__LEFT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINEXPR__OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINEXPR__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Binexpr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINEXPR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.IntValueImpl <em>Int Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.IntValueImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getIntValue()
   * @generated
   */
  int INT_VALUE = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Int Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.StringValueImpl <em>String Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.StringValueImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getStringValue()
   * @generated
   */
  int STRING_VALUE = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>String Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Programme <em>Programme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programme</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Programme
   * @generated
   */
  EClass getProgramme();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.idmdsl.Programme#getLoadscopes <em>Loadscopes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Loadscopes</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Programme#getLoadscopes()
   * @see #getProgramme()
   * @generated
   */
  EReference getProgramme_Loadscopes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Loadscope <em>Loadscope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loadscope</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Loadscope
   * @generated
   */
  EClass getLoadscope();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.Loadscope#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Loadscope#getUrl()
   * @see #getLoadscope()
   * @generated
   */
  EAttribute getLoadscope_Url();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.idmdsl.Loadscope#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Loadscope#getInstructions()
   * @see #getLoadscope()
   * @generated
   */
  EReference getLoadscope_Instructions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.InsertCol <em>Insert Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert Col</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertCol
   * @generated
   */
  EClass getInsertCol();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.InsertCol#getColIndex <em>Col Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertCol#getColIndex()
   * @see #getInsertCol()
   * @generated
   */
  EReference getInsertCol_ColIndex();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.InsertCol#getColName <em>Col Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Col Name</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertCol#getColName()
   * @see #getInsertCol()
   * @generated
   */
  EAttribute getInsertCol_ColName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.RemoveCol <em>Remove Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Remove Col</em>'.
   * @see org.xtext.example.mydsl.idmdsl.RemoveCol
   * @generated
   */
  EClass getRemoveCol();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.RemoveCol#getColIndex <em>Col Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.RemoveCol#getColIndex()
   * @see #getRemoveCol()
   * @generated
   */
  EReference getRemoveCol_ColIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.InsertLine <em>Insert Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert Line</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertLine
   * @generated
   */
  EClass getInsertLine();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.InsertLine#getLineIndex <em>Line Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertLine#getLineIndex()
   * @see #getInsertLine()
   * @generated
   */
  EReference getInsertLine_LineIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.RemoveLine <em>Remove Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Remove Line</em>'.
   * @see org.xtext.example.mydsl.idmdsl.RemoveLine
   * @generated
   */
  EClass getRemoveLine();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.RemoveLine#getLineIndex <em>Line Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.RemoveLine#getLineIndex()
   * @see #getRemoveLine()
   * @generated
   */
  EReference getRemoveLine_LineIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Modify <em>Modify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modify</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Modify
   * @generated
   */
  EClass getModify();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Modify#getColIndex <em>Col Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Modify#getColIndex()
   * @see #getModify()
   * @generated
   */
  EReference getModify_ColIndex();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Modify#getRowIndex <em>Row Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Row Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Modify#getRowIndex()
   * @see #getModify()
   * @generated
   */
  EReference getModify_RowIndex();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Modify#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Modify#getValue()
   * @see #getModify()
   * @generated
   */
  EReference getModify_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Print#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Print#getValue()
   * @see #getPrint()
   * @generated
   */
  EReference getPrint_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Store <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Store
   * @generated
   */
  EClass getStore();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.Store#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Store#getUrl()
   * @see #getStore()
   * @generated
   */
  EAttribute getStore_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Export <em>Export</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Export</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Export
   * @generated
   */
  EClass getExport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.Export#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Export#getUrl()
   * @see #getExport()
   * @generated
   */
  EAttribute getExport_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Expression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Expression#getValue()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.PrimaryExpression <em>Primary Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primary Expression</em>'.
   * @see org.xtext.example.mydsl.idmdsl.PrimaryExpression
   * @generated
   */
  EClass getPrimaryExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.PrimaryExpression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.PrimaryExpression#getValue()
   * @see #getPrimaryExpression()
   * @generated
   */
  EReference getPrimaryExpression_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Selectcell <em>Selectcell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selectcell</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Selectcell
   * @generated
   */
  EClass getSelectcell();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Selectcell#getCellX <em>Cell X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cell X</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Selectcell#getCellX()
   * @see #getSelectcell()
   * @generated
   */
  EReference getSelectcell_CellX();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Selectcell#getCellY <em>Cell Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cell Y</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Selectcell#getCellY()
   * @see #getSelectcell()
   * @generated
   */
  EReference getSelectcell_CellY();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Linesum <em>Linesum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Linesum</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Linesum
   * @generated
   */
  EClass getLinesum();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Linesum#getLineIndex <em>Line Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Linesum#getLineIndex()
   * @see #getLinesum()
   * @generated
   */
  EReference getLinesum_LineIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Colsum <em>Colsum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colsum</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colsum
   * @generated
   */
  EClass getColsum();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Colsum#getColIndex <em>Col Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colsum#getColIndex()
   * @see #getColsum()
   * @generated
   */
  EReference getColsum_ColIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Lineprod <em>Lineprod</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lineprod</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Lineprod
   * @generated
   */
  EClass getLineprod();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Lineprod#getLineIndex <em>Line Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Lineprod#getLineIndex()
   * @see #getLineprod()
   * @generated
   */
  EReference getLineprod_LineIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Colprod <em>Colprod</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colprod</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colprod
   * @generated
   */
  EClass getColprod();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Colprod#getColIndex <em>Col Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colprod#getColIndex()
   * @see #getColprod()
   * @generated
   */
  EReference getColprod_ColIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Binexpr <em>Binexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binexpr</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Binexpr
   * @generated
   */
  EClass getBinexpr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Binexpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Binexpr#getLeft()
   * @see #getBinexpr()
   * @generated
   */
  EReference getBinexpr_Left();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.Binexpr#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Binexpr#getOp()
   * @see #getBinexpr()
   * @generated
   */
  EAttribute getBinexpr_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Binexpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Binexpr#getRight()
   * @see #getBinexpr()
   * @generated
   */
  EReference getBinexpr_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.IntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.IntValue
   * @generated
   */
  EClass getIntValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.IntValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.IntValue#getValue()
   * @see #getIntValue()
   * @generated
   */
  EAttribute getIntValue_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.StringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.StringValue
   * @generated
   */
  EClass getStringValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.StringValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.StringValue#getValue()
   * @see #getStringValue()
   * @generated
   */
  EAttribute getStringValue_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IdmdslFactory getIdmdslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ProgrammeImpl <em>Programme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ProgrammeImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getProgramme()
     * @generated
     */
    EClass PROGRAMME = eINSTANCE.getProgramme();

    /**
     * The meta object literal for the '<em><b>Loadscopes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMME__LOADSCOPES = eINSTANCE.getProgramme_Loadscopes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.LoadscopeImpl <em>Loadscope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.LoadscopeImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLoadscope()
     * @generated
     */
    EClass LOADSCOPE = eINSTANCE.getLoadscope();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOADSCOPE__URL = eINSTANCE.getLoadscope_Url();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOADSCOPE__INSTRUCTIONS = eINSTANCE.getLoadscope_Instructions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.InstructionImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertColImpl <em>Insert Col</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.InsertColImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsertCol()
     * @generated
     */
    EClass INSERT_COL = eINSTANCE.getInsertCol();

    /**
     * The meta object literal for the '<em><b>Col Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_COL__COL_INDEX = eINSTANCE.getInsertCol_ColIndex();

    /**
     * The meta object literal for the '<em><b>Col Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_COL__COL_NAME = eINSTANCE.getInsertCol_ColName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.RemoveColImpl <em>Remove Col</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.RemoveColImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getRemoveCol()
     * @generated
     */
    EClass REMOVE_COL = eINSTANCE.getRemoveCol();

    /**
     * The meta object literal for the '<em><b>Col Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REMOVE_COL__COL_INDEX = eINSTANCE.getRemoveCol_ColIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertLineImpl <em>Insert Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.InsertLineImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsertLine()
     * @generated
     */
    EClass INSERT_LINE = eINSTANCE.getInsertLine();

    /**
     * The meta object literal for the '<em><b>Line Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_LINE__LINE_INDEX = eINSTANCE.getInsertLine_LineIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.RemoveLineImpl <em>Remove Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.RemoveLineImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getRemoveLine()
     * @generated
     */
    EClass REMOVE_LINE = eINSTANCE.getRemoveLine();

    /**
     * The meta object literal for the '<em><b>Line Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REMOVE_LINE__LINE_INDEX = eINSTANCE.getRemoveLine_LineIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ModifyImpl <em>Modify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ModifyImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getModify()
     * @generated
     */
    EClass MODIFY = eINSTANCE.getModify();

    /**
     * The meta object literal for the '<em><b>Col Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODIFY__COL_INDEX = eINSTANCE.getModify_ColIndex();

    /**
     * The meta object literal for the '<em><b>Row Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODIFY__ROW_INDEX = eINSTANCE.getModify_RowIndex();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODIFY__VALUE = eINSTANCE.getModify_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.PrintImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT__VALUE = eINSTANCE.getPrint_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.StoreImpl <em>Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.StoreImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getStore()
     * @generated
     */
    EClass STORE = eINSTANCE.getStore();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORE__URL = eINSTANCE.getStore_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExportImpl <em>Export</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ExportImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExport()
     * @generated
     */
    EClass EXPORT = eINSTANCE.getExport();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPORT__URL = eINSTANCE.getExport_Url();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ExpressionImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__VALUE = eINSTANCE.getExpression_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.PrimaryExpressionImpl <em>Primary Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.PrimaryExpressionImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getPrimaryExpression()
     * @generated
     */
    EClass PRIMARY_EXPRESSION = eINSTANCE.getPrimaryExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIMARY_EXPRESSION__VALUE = eINSTANCE.getPrimaryExpression_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl <em>Selectcell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getSelectcell()
     * @generated
     */
    EClass SELECTCELL = eINSTANCE.getSelectcell();

    /**
     * The meta object literal for the '<em><b>Cell X</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTCELL__CELL_X = eINSTANCE.getSelectcell_CellX();

    /**
     * The meta object literal for the '<em><b>Cell Y</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTCELL__CELL_Y = eINSTANCE.getSelectcell_CellY();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.LinesumImpl <em>Linesum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.LinesumImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLinesum()
     * @generated
     */
    EClass LINESUM = eINSTANCE.getLinesum();

    /**
     * The meta object literal for the '<em><b>Line Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINESUM__LINE_INDEX = eINSTANCE.getLinesum_LineIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ColsumImpl <em>Colsum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ColsumImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getColsum()
     * @generated
     */
    EClass COLSUM = eINSTANCE.getColsum();

    /**
     * The meta object literal for the '<em><b>Col Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLSUM__COL_INDEX = eINSTANCE.getColsum_ColIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.LineprodImpl <em>Lineprod</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.LineprodImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLineprod()
     * @generated
     */
    EClass LINEPROD = eINSTANCE.getLineprod();

    /**
     * The meta object literal for the '<em><b>Line Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINEPROD__LINE_INDEX = eINSTANCE.getLineprod_LineIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ColprodImpl <em>Colprod</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ColprodImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getColprod()
     * @generated
     */
    EClass COLPROD = eINSTANCE.getColprod();

    /**
     * The meta object literal for the '<em><b>Col Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLPROD__COL_INDEX = eINSTANCE.getColprod_ColIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.BinexprImpl <em>Binexpr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.BinexprImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getBinexpr()
     * @generated
     */
    EClass BINEXPR = eINSTANCE.getBinexpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINEXPR__LEFT = eINSTANCE.getBinexpr_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BINEXPR__OP = eINSTANCE.getBinexpr_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINEXPR__RIGHT = eINSTANCE.getBinexpr_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.IntValueImpl <em>Int Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.IntValueImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getIntValue()
     * @generated
     */
    EClass INT_VALUE = eINSTANCE.getIntValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_VALUE__VALUE = eINSTANCE.getIntValue_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.StringValueImpl <em>String Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.StringValueImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getStringValue()
     * @generated
     */
    EClass STRING_VALUE = eINSTANCE.getStringValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VALUE__VALUE = eINSTANCE.getStringValue_Value();

  }

} //IdmdslPackage
