/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.idmdsl.IdmdslFactory
 * @model kind="package"
 * @generated
 */
public interface IdmdslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "idmdsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "idmdsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IdmdslPackage eINSTANCE = org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ProgrammeImpl <em>Programme</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ProgrammeImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getProgramme()
   * @generated
   */
  int PROGRAMME = 0;

  /**
   * The feature id for the '<em><b>Loadscopes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME__LOADSCOPES = 0;

  /**
   * The number of structural features of the '<em>Programme</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.LoadscopeImpl <em>Loadscope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.LoadscopeImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLoadscope()
   * @generated
   */
  int LOADSCOPE = 1;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOADSCOPE__INSTRUCTIONS = 0;

  /**
   * The number of structural features of the '<em>Loadscope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOADSCOPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.LoadImpl <em>Load</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.LoadImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLoad()
   * @generated
   */
  int LOAD = 2;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD__INSTRUCTIONS = LOADSCOPE__INSTRUCTIONS;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD__PATH = LOADSCOPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Load</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_FEATURE_COUNT = LOADSCOPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.CreateImpl <em>Create</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.CreateImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getCreate()
   * @generated
   */
  int CREATE = 3;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE__INSTRUCTIONS = LOADSCOPE__INSTRUCTIONS;

  /**
   * The number of structural features of the '<em>Create</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FEATURE_COUNT = LOADSCOPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.InstructionImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 4;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertColImpl <em>Insert Col</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.InsertColImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsertCol()
   * @generated
   */
  int INSERT_COL = 5;

  /**
   * The feature id for the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_COL__COL_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Col Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_COL__COL_NAME = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_COL__EXP = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Insert Col</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_COL_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.RemoveColImpl <em>Remove Col</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.RemoveColImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getRemoveCol()
   * @generated
   */
  int REMOVE_COL = 6;

  /**
   * The feature id for the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_COL__COL_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_COL__NAME = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Remove Col</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_COL_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertLineImpl <em>Insert Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.InsertLineImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsertLine()
   * @generated
   */
  int INSERT_LINE = 7;

  /**
   * The feature id for the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_LINE__LINE_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_LINE__EXPS = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Insert Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_LINE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.RemoveLineImpl <em>Remove Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.RemoveLineImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getRemoveLine()
   * @generated
   */
  int REMOVE_LINE = 8;

  /**
   * The feature id for the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_LINE__LINE_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Remove Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REMOVE_LINE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertImpl <em>Insert</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.InsertImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsert()
   * @generated
   */
  int INSERT = 9;

  /**
   * The feature id for the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__LINE_INDEX = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Col Name Or Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__COL_NAME_OR_INDEX = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT__VALUE = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Insert</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSERT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.PrintImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__VALUE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExportCSVImpl <em>Export CSV</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ExportCSVImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExportCSV()
   * @generated
   */
  int EXPORT_CSV = 11;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT_CSV__PATH = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Export CSV</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT_CSV_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExportJSONImpl <em>Export JSON</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ExportJSONImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExportJSON()
   * @generated
   */
  int EXPORT_JSON = 12;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT_JSON__PATH = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Export JSON</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPORT_JSON_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ExpressionImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 13;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.PrimaryExpressionImpl <em>Primary Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.PrimaryExpressionImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getPrimaryExpression()
   * @generated
   */
  int PRIMARY_EXPRESSION = 14;

  /**
   * The number of structural features of the '<em>Primary Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl <em>Selectcell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getSelectcell()
   * @generated
   */
  int SELECTCELL = 15;

  /**
   * The feature id for the '<em><b>Cell X</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTCELL__CELL_X = PRIMARY_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cell Y</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTCELL__CELL_Y = PRIMARY_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Selectcell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTCELL_FEATURE_COUNT = PRIMARY_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.LinesumImpl <em>Linesum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.LinesumImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLinesum()
   * @generated
   */
  int LINESUM = 16;

  /**
   * The feature id for the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINESUM__LINE_INDEX = PRIMARY_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Linesum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINESUM_FEATURE_COUNT = PRIMARY_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ColsumImpl <em>Colsum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ColsumImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getColsum()
   * @generated
   */
  int COLSUM = 17;

  /**
   * The feature id for the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLSUM__COL_INDEX = PRIMARY_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLSUM__NAME = PRIMARY_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Colsum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLSUM_FEATURE_COUNT = PRIMARY_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.LineprodImpl <em>Lineprod</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.LineprodImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLineprod()
   * @generated
   */
  int LINEPROD = 18;

  /**
   * The feature id for the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEPROD__LINE_INDEX = PRIMARY_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Lineprod</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEPROD_FEATURE_COUNT = PRIMARY_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.ColprodImpl <em>Colprod</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.ColprodImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getColprod()
   * @generated
   */
  int COLPROD = 19;

  /**
   * The feature id for the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLPROD__COL_INDEX = PRIMARY_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLPROD__NAME = PRIMARY_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Colprod</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLPROD_FEATURE_COUNT = PRIMARY_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.BinexprImpl <em>Binexpr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.BinexprImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getBinexpr()
   * @generated
   */
  int BINEXPR = 20;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINEXPR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINEXPR__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINEXPR__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Binexpr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINEXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.NoneValueImpl <em>None Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.NoneValueImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getNoneValue()
   * @generated
   */
  int NONE_VALUE = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NONE_VALUE__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>None Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NONE_VALUE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.IntValueImpl <em>Int Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.IntValueImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getIntValue()
   * @generated
   */
  int INT_VALUE = 22;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE__VALUE = PRIMARY_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE_FEATURE_COUNT = PRIMARY_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.idmdsl.impl.StringValueImpl <em>String Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.idmdsl.impl.StringValueImpl
   * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getStringValue()
   * @generated
   */
  int STRING_VALUE = 23;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>String Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Programme <em>Programme</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Programme</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Programme
   * @generated
   */
  EClass getProgramme();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.idmdsl.Programme#getLoadscopes <em>Loadscopes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Loadscopes</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Programme#getLoadscopes()
   * @see #getProgramme()
   * @generated
   */
  EReference getProgramme_Loadscopes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Loadscope <em>Loadscope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loadscope</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Loadscope
   * @generated
   */
  EClass getLoadscope();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.idmdsl.Loadscope#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Loadscope#getInstructions()
   * @see #getLoadscope()
   * @generated
   */
  EReference getLoadscope_Instructions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Load <em>Load</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Load</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Load
   * @generated
   */
  EClass getLoad();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.Load#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Load#getPath()
   * @see #getLoad()
   * @generated
   */
  EAttribute getLoad_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Create <em>Create</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Create
   * @generated
   */
  EClass getCreate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.InsertCol <em>Insert Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert Col</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertCol
   * @generated
   */
  EClass getInsertCol();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.InsertCol#getColIndex <em>Col Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertCol#getColIndex()
   * @see #getInsertCol()
   * @generated
   */
  EReference getInsertCol_ColIndex();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.InsertCol#getColName <em>Col Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Col Name</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertCol#getColName()
   * @see #getInsertCol()
   * @generated
   */
  EAttribute getInsertCol_ColName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.InsertCol#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertCol#getExp()
   * @see #getInsertCol()
   * @generated
   */
  EReference getInsertCol_Exp();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.RemoveCol <em>Remove Col</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Remove Col</em>'.
   * @see org.xtext.example.mydsl.idmdsl.RemoveCol
   * @generated
   */
  EClass getRemoveCol();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.RemoveCol#getColIndex <em>Col Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.RemoveCol#getColIndex()
   * @see #getRemoveCol()
   * @generated
   */
  EReference getRemoveCol_ColIndex();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.RemoveCol#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.idmdsl.RemoveCol#getName()
   * @see #getRemoveCol()
   * @generated
   */
  EAttribute getRemoveCol_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.InsertLine <em>Insert Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert Line</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertLine
   * @generated
   */
  EClass getInsertLine();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.InsertLine#getLineIndex <em>Line Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertLine#getLineIndex()
   * @see #getInsertLine()
   * @generated
   */
  EReference getInsertLine_LineIndex();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.idmdsl.InsertLine#getExps <em>Exps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exps</em>'.
   * @see org.xtext.example.mydsl.idmdsl.InsertLine#getExps()
   * @see #getInsertLine()
   * @generated
   */
  EReference getInsertLine_Exps();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.RemoveLine <em>Remove Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Remove Line</em>'.
   * @see org.xtext.example.mydsl.idmdsl.RemoveLine
   * @generated
   */
  EClass getRemoveLine();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.RemoveLine#getLineIndex <em>Line Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.RemoveLine#getLineIndex()
   * @see #getRemoveLine()
   * @generated
   */
  EReference getRemoveLine_LineIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Insert <em>Insert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insert</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Insert
   * @generated
   */
  EClass getInsert();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Insert#getLineIndex <em>Line Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Insert#getLineIndex()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_LineIndex();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Insert#getColNameOrIndex <em>Col Name Or Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Name Or Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Insert#getColNameOrIndex()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_ColNameOrIndex();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Insert#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Insert#getValue()
   * @see #getInsert()
   * @generated
   */
  EReference getInsert_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Print#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Print#getValue()
   * @see #getPrint()
   * @generated
   */
  EReference getPrint_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.ExportCSV <em>Export CSV</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Export CSV</em>'.
   * @see org.xtext.example.mydsl.idmdsl.ExportCSV
   * @generated
   */
  EClass getExportCSV();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.ExportCSV#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.idmdsl.ExportCSV#getPath()
   * @see #getExportCSV()
   * @generated
   */
  EAttribute getExportCSV_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.ExportJSON <em>Export JSON</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Export JSON</em>'.
   * @see org.xtext.example.mydsl.idmdsl.ExportJSON
   * @generated
   */
  EClass getExportJSON();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.ExportJSON#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.idmdsl.ExportJSON#getPath()
   * @see #getExportJSON()
   * @generated
   */
  EAttribute getExportJSON_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.PrimaryExpression <em>Primary Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primary Expression</em>'.
   * @see org.xtext.example.mydsl.idmdsl.PrimaryExpression
   * @generated
   */
  EClass getPrimaryExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Selectcell <em>Selectcell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selectcell</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Selectcell
   * @generated
   */
  EClass getSelectcell();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Selectcell#getCellX <em>Cell X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cell X</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Selectcell#getCellX()
   * @see #getSelectcell()
   * @generated
   */
  EReference getSelectcell_CellX();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Selectcell#getCellY <em>Cell Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cell Y</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Selectcell#getCellY()
   * @see #getSelectcell()
   * @generated
   */
  EReference getSelectcell_CellY();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Linesum <em>Linesum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Linesum</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Linesum
   * @generated
   */
  EClass getLinesum();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Linesum#getLineIndex <em>Line Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Linesum#getLineIndex()
   * @see #getLinesum()
   * @generated
   */
  EReference getLinesum_LineIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Colsum <em>Colsum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colsum</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colsum
   * @generated
   */
  EClass getColsum();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Colsum#getColIndex <em>Col Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colsum#getColIndex()
   * @see #getColsum()
   * @generated
   */
  EReference getColsum_ColIndex();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.Colsum#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colsum#getName()
   * @see #getColsum()
   * @generated
   */
  EAttribute getColsum_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Lineprod <em>Lineprod</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lineprod</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Lineprod
   * @generated
   */
  EClass getLineprod();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Lineprod#getLineIndex <em>Line Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Line Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Lineprod#getLineIndex()
   * @see #getLineprod()
   * @generated
   */
  EReference getLineprod_LineIndex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Colprod <em>Colprod</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Colprod</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colprod
   * @generated
   */
  EClass getColprod();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Colprod#getColIndex <em>Col Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Col Index</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colprod#getColIndex()
   * @see #getColprod()
   * @generated
   */
  EReference getColprod_ColIndex();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.Colprod#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Colprod#getName()
   * @see #getColprod()
   * @generated
   */
  EAttribute getColprod_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.Binexpr <em>Binexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binexpr</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Binexpr
   * @generated
   */
  EClass getBinexpr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Binexpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Binexpr#getLeft()
   * @see #getBinexpr()
   * @generated
   */
  EReference getBinexpr_Left();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.Binexpr#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Binexpr#getOp()
   * @see #getBinexpr()
   * @generated
   */
  EAttribute getBinexpr_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.idmdsl.Binexpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.idmdsl.Binexpr#getRight()
   * @see #getBinexpr()
   * @generated
   */
  EReference getBinexpr_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.NoneValue <em>None Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>None Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.NoneValue
   * @generated
   */
  EClass getNoneValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.NoneValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.NoneValue#getValue()
   * @see #getNoneValue()
   * @generated
   */
  EAttribute getNoneValue_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.IntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.IntValue
   * @generated
   */
  EClass getIntValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.IntValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.IntValue#getValue()
   * @see #getIntValue()
   * @generated
   */
  EAttribute getIntValue_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.idmdsl.StringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.StringValue
   * @generated
   */
  EClass getStringValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.idmdsl.StringValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.idmdsl.StringValue#getValue()
   * @see #getStringValue()
   * @generated
   */
  EAttribute getStringValue_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IdmdslFactory getIdmdslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ProgrammeImpl <em>Programme</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ProgrammeImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getProgramme()
     * @generated
     */
    EClass PROGRAMME = eINSTANCE.getProgramme();

    /**
     * The meta object literal for the '<em><b>Loadscopes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMME__LOADSCOPES = eINSTANCE.getProgramme_Loadscopes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.LoadscopeImpl <em>Loadscope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.LoadscopeImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLoadscope()
     * @generated
     */
    EClass LOADSCOPE = eINSTANCE.getLoadscope();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOADSCOPE__INSTRUCTIONS = eINSTANCE.getLoadscope_Instructions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.LoadImpl <em>Load</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.LoadImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLoad()
     * @generated
     */
    EClass LOAD = eINSTANCE.getLoad();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD__PATH = eINSTANCE.getLoad_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.CreateImpl <em>Create</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.CreateImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getCreate()
     * @generated
     */
    EClass CREATE = eINSTANCE.getCreate();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.InstructionImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertColImpl <em>Insert Col</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.InsertColImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsertCol()
     * @generated
     */
    EClass INSERT_COL = eINSTANCE.getInsertCol();

    /**
     * The meta object literal for the '<em><b>Col Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_COL__COL_INDEX = eINSTANCE.getInsertCol_ColIndex();

    /**
     * The meta object literal for the '<em><b>Col Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSERT_COL__COL_NAME = eINSTANCE.getInsertCol_ColName();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_COL__EXP = eINSTANCE.getInsertCol_Exp();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.RemoveColImpl <em>Remove Col</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.RemoveColImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getRemoveCol()
     * @generated
     */
    EClass REMOVE_COL = eINSTANCE.getRemoveCol();

    /**
     * The meta object literal for the '<em><b>Col Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REMOVE_COL__COL_INDEX = eINSTANCE.getRemoveCol_ColIndex();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REMOVE_COL__NAME = eINSTANCE.getRemoveCol_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertLineImpl <em>Insert Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.InsertLineImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsertLine()
     * @generated
     */
    EClass INSERT_LINE = eINSTANCE.getInsertLine();

    /**
     * The meta object literal for the '<em><b>Line Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_LINE__LINE_INDEX = eINSTANCE.getInsertLine_LineIndex();

    /**
     * The meta object literal for the '<em><b>Exps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT_LINE__EXPS = eINSTANCE.getInsertLine_Exps();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.RemoveLineImpl <em>Remove Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.RemoveLineImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getRemoveLine()
     * @generated
     */
    EClass REMOVE_LINE = eINSTANCE.getRemoveLine();

    /**
     * The meta object literal for the '<em><b>Line Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REMOVE_LINE__LINE_INDEX = eINSTANCE.getRemoveLine_LineIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.InsertImpl <em>Insert</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.InsertImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getInsert()
     * @generated
     */
    EClass INSERT = eINSTANCE.getInsert();

    /**
     * The meta object literal for the '<em><b>Line Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__LINE_INDEX = eINSTANCE.getInsert_LineIndex();

    /**
     * The meta object literal for the '<em><b>Col Name Or Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__COL_NAME_OR_INDEX = eINSTANCE.getInsert_ColNameOrIndex();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSERT__VALUE = eINSTANCE.getInsert_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.PrintImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT__VALUE = eINSTANCE.getPrint_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExportCSVImpl <em>Export CSV</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ExportCSVImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExportCSV()
     * @generated
     */
    EClass EXPORT_CSV = eINSTANCE.getExportCSV();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPORT_CSV__PATH = eINSTANCE.getExportCSV_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExportJSONImpl <em>Export JSON</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ExportJSONImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExportJSON()
     * @generated
     */
    EClass EXPORT_JSON = eINSTANCE.getExportJSON();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPORT_JSON__PATH = eINSTANCE.getExportJSON_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ExpressionImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.PrimaryExpressionImpl <em>Primary Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.PrimaryExpressionImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getPrimaryExpression()
     * @generated
     */
    EClass PRIMARY_EXPRESSION = eINSTANCE.getPrimaryExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl <em>Selectcell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getSelectcell()
     * @generated
     */
    EClass SELECTCELL = eINSTANCE.getSelectcell();

    /**
     * The meta object literal for the '<em><b>Cell X</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTCELL__CELL_X = eINSTANCE.getSelectcell_CellX();

    /**
     * The meta object literal for the '<em><b>Cell Y</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECTCELL__CELL_Y = eINSTANCE.getSelectcell_CellY();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.LinesumImpl <em>Linesum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.LinesumImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLinesum()
     * @generated
     */
    EClass LINESUM = eINSTANCE.getLinesum();

    /**
     * The meta object literal for the '<em><b>Line Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINESUM__LINE_INDEX = eINSTANCE.getLinesum_LineIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ColsumImpl <em>Colsum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ColsumImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getColsum()
     * @generated
     */
    EClass COLSUM = eINSTANCE.getColsum();

    /**
     * The meta object literal for the '<em><b>Col Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLSUM__COL_INDEX = eINSTANCE.getColsum_ColIndex();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLSUM__NAME = eINSTANCE.getColsum_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.LineprodImpl <em>Lineprod</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.LineprodImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getLineprod()
     * @generated
     */
    EClass LINEPROD = eINSTANCE.getLineprod();

    /**
     * The meta object literal for the '<em><b>Line Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINEPROD__LINE_INDEX = eINSTANCE.getLineprod_LineIndex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.ColprodImpl <em>Colprod</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.ColprodImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getColprod()
     * @generated
     */
    EClass COLPROD = eINSTANCE.getColprod();

    /**
     * The meta object literal for the '<em><b>Col Index</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLPROD__COL_INDEX = eINSTANCE.getColprod_ColIndex();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLPROD__NAME = eINSTANCE.getColprod_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.BinexprImpl <em>Binexpr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.BinexprImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getBinexpr()
     * @generated
     */
    EClass BINEXPR = eINSTANCE.getBinexpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINEXPR__LEFT = eINSTANCE.getBinexpr_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BINEXPR__OP = eINSTANCE.getBinexpr_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINEXPR__RIGHT = eINSTANCE.getBinexpr_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.NoneValueImpl <em>None Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.NoneValueImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getNoneValue()
     * @generated
     */
    EClass NONE_VALUE = eINSTANCE.getNoneValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NONE_VALUE__VALUE = eINSTANCE.getNoneValue_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.IntValueImpl <em>Int Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.IntValueImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getIntValue()
     * @generated
     */
    EClass INT_VALUE = eINSTANCE.getIntValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_VALUE__VALUE = eINSTANCE.getIntValue_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.idmdsl.impl.StringValueImpl <em>String Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.idmdsl.impl.StringValueImpl
     * @see org.xtext.example.mydsl.idmdsl.impl.IdmdslPackageImpl#getStringValue()
     * @generated
     */
    EClass STRING_VALUE = eINSTANCE.getStringValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VALUE__VALUE = eINSTANCE.getStringValue_Value();

  }

} //IdmdslPackage
