/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.Insert#getLineIndex <em>Line Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.Insert#getColNameOrIndex <em>Col Name Or Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.Insert#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends Instruction
{
  /**
   * Returns the value of the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line Index</em>' containment reference.
   * @see #setLineIndex(Expression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsert_LineIndex()
   * @model containment="true"
   * @generated
   */
  Expression getLineIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.Insert#getLineIndex <em>Line Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Line Index</em>' containment reference.
   * @see #getLineIndex()
   * @generated
   */
  void setLineIndex(Expression value);

  /**
   * Returns the value of the '<em><b>Col Name Or Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col Name Or Index</em>' containment reference.
   * @see #setColNameOrIndex(Expression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsert_ColNameOrIndex()
   * @model containment="true"
   * @generated
   */
  Expression getColNameOrIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.Insert#getColNameOrIndex <em>Col Name Or Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col Name Or Index</em>' containment reference.
   * @see #getColNameOrIndex()
   * @generated
   */
  void setColNameOrIndex(Expression value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(EObject)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsert_Value()
   * @model containment="true"
   * @generated
   */
  EObject getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.Insert#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(EObject value);

} // Insert
