/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert Col</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.InsertCol#getColIndex <em>Col Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.InsertCol#getColName <em>Col Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.InsertCol#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsertCol()
 * @model
 * @generated
 */
public interface InsertCol extends Instruction
{
  /**
   * Returns the value of the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col Index</em>' containment reference.
   * @see #setColIndex(Expression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsertCol_ColIndex()
   * @model containment="true"
   * @generated
   */
  Expression getColIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.InsertCol#getColIndex <em>Col Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col Index</em>' containment reference.
   * @see #getColIndex()
   * @generated
   */
  void setColIndex(Expression value);

  /**
   * Returns the value of the '<em><b>Col Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col Name</em>' attribute.
   * @see #setColName(String)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsertCol_ColName()
   * @model
   * @generated
   */
  String getColName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.InsertCol#getColName <em>Col Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col Name</em>' attribute.
   * @see #getColName()
   * @generated
   */
  void setColName(String value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsertCol_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.InsertCol#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

} // InsertCol
