/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.Insert#getLineIndex <em>Line Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.Insert#getColName <em>Col Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.Insert#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends Instruction
{
  /**
   * Returns the value of the '<em><b>Line Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Line Index</em>' containment reference.
   * @see #setLineIndex(MathExpression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsert_LineIndex()
   * @model containment="true"
   * @generated
   */
  MathExpression getLineIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.Insert#getLineIndex <em>Line Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Line Index</em>' containment reference.
   * @see #getLineIndex()
   * @generated
   */
  void setLineIndex(MathExpression value);

  /**
   * Returns the value of the '<em><b>Col Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col Name</em>' containment reference.
   * @see #setColName(StringValue)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsert_ColName()
   * @model containment="true"
   * @generated
   */
  StringValue getColName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.Insert#getColName <em>Col Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col Name</em>' containment reference.
   * @see #getColName()
   * @generated
   */
  void setColName(StringValue value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Expression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInsert_Value()
   * @model containment="true"
   * @generated
   */
  Expression getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.Insert#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Expression value);

} // Insert
