/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getInstruction()
 * @model
 * @generated
 */
public interface Instruction extends EObject
{
} // Instruction
