/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Modify</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.Modify#getColIndex <em>Col Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.Modify#getRowIndex <em>Row Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.Modify#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getModify()
 * @model
 * @generated
 */
public interface Modify extends Instruction
{
  /**
   * Returns the value of the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col Index</em>' containment reference.
   * @see #setColIndex(Expression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getModify_ColIndex()
   * @model containment="true"
   * @generated
   */
  Expression getColIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.Modify#getColIndex <em>Col Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col Index</em>' containment reference.
   * @see #getColIndex()
   * @generated
   */
  void setColIndex(Expression value);

  /**
   * Returns the value of the '<em><b>Row Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row Index</em>' containment reference.
   * @see #setRowIndex(Expression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getModify_RowIndex()
   * @model containment="true"
   * @generated
   */
  Expression getRowIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.Modify#getRowIndex <em>Row Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row Index</em>' containment reference.
   * @see #getRowIndex()
   * @generated
   */
  void setRowIndex(Expression value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(EObject)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getModify_Value()
   * @model containment="true"
   * @generated
   */
  EObject getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.Modify#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(EObject value);

} // Modify
