/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Remove Col</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.RemoveCol#getColIndex <em>Col Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.RemoveCol#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getRemoveCol()
 * @model
 * @generated
 */
public interface RemoveCol extends Instruction
{
  /**
   * Returns the value of the '<em><b>Col Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Col Index</em>' containment reference.
   * @see #setColIndex(Expression)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getRemoveCol_ColIndex()
   * @model containment="true"
   * @generated
   */
  Expression getColIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.RemoveCol#getColIndex <em>Col Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Col Index</em>' containment reference.
   * @see #getColIndex()
   * @generated
   */
  void setColIndex(Expression value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.idmdsl.IdmdslPackage#getRemoveCol_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.idmdsl.RemoveCol#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // RemoveCol
