/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.idmdsl.Binexpr;
import org.xtext.example.mydsl.idmdsl.Colprod;
import org.xtext.example.mydsl.idmdsl.Colsum;
import org.xtext.example.mydsl.idmdsl.Export;
import org.xtext.example.mydsl.idmdsl.Expression;
import org.xtext.example.mydsl.idmdsl.IdmdslPackage;
import org.xtext.example.mydsl.idmdsl.InsertCol;
import org.xtext.example.mydsl.idmdsl.InsertLine;
import org.xtext.example.mydsl.idmdsl.IntValue;
import org.xtext.example.mydsl.idmdsl.Lineprod;
import org.xtext.example.mydsl.idmdsl.Linesum;
import org.xtext.example.mydsl.idmdsl.Loadscope;
import org.xtext.example.mydsl.idmdsl.Modify;
import org.xtext.example.mydsl.idmdsl.PrimaryExpression;
import org.xtext.example.mydsl.idmdsl.Print;
import org.xtext.example.mydsl.idmdsl.Programme;
import org.xtext.example.mydsl.idmdsl.RemoveCol;
import org.xtext.example.mydsl.idmdsl.RemoveLine;
import org.xtext.example.mydsl.idmdsl.Selectcell;
import org.xtext.example.mydsl.idmdsl.Store;
import org.xtext.example.mydsl.idmdsl.StringValue;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == IdmdslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case IdmdslPackage.BINEXPR:
				sequence_Binexpr(context, (Binexpr) semanticObject); 
				return; 
			case IdmdslPackage.COLPROD:
				sequence_Colprod(context, (Colprod) semanticObject); 
				return; 
			case IdmdslPackage.COLSUM:
				sequence_Colsum(context, (Colsum) semanticObject); 
				return; 
			case IdmdslPackage.EXPORT:
				sequence_Export(context, (Export) semanticObject); 
				return; 
			case IdmdslPackage.EXPRESSION:
				sequence_Expression(context, (Expression) semanticObject); 
				return; 
			case IdmdslPackage.INSERT_COL:
				sequence_InsertCol(context, (InsertCol) semanticObject); 
				return; 
			case IdmdslPackage.INSERT_LINE:
				sequence_InsertLine(context, (InsertLine) semanticObject); 
				return; 
			case IdmdslPackage.INT_VALUE:
				sequence_IntValue(context, (IntValue) semanticObject); 
				return; 
			case IdmdslPackage.LINEPROD:
				sequence_Lineprod(context, (Lineprod) semanticObject); 
				return; 
			case IdmdslPackage.LINESUM:
				sequence_Linesum(context, (Linesum) semanticObject); 
				return; 
			case IdmdslPackage.LOADSCOPE:
				sequence_Loadscope(context, (Loadscope) semanticObject); 
				return; 
			case IdmdslPackage.MODIFY:
				sequence_Modify(context, (Modify) semanticObject); 
				return; 
			case IdmdslPackage.PRIMARY_EXPRESSION:
				sequence_PrimaryExpression(context, (PrimaryExpression) semanticObject); 
				return; 
			case IdmdslPackage.PRINT:
				sequence_Print(context, (Print) semanticObject); 
				return; 
			case IdmdslPackage.PROGRAMME:
				sequence_Programme(context, (Programme) semanticObject); 
				return; 
			case IdmdslPackage.REMOVE_COL:
				sequence_RemoveCol(context, (RemoveCol) semanticObject); 
				return; 
			case IdmdslPackage.REMOVE_LINE:
				sequence_RemoveLine(context, (RemoveLine) semanticObject); 
				return; 
			case IdmdslPackage.SELECTCELL:
				sequence_Selectcell(context, (Selectcell) semanticObject); 
				return; 
			case IdmdslPackage.STORE:
				sequence_Store(context, (Store) semanticObject); 
				return; 
			case IdmdslPackage.STRING_VALUE:
				sequence_StringValue(context, (StringValue) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Binexpr returns Binexpr
	 *
	 * Constraint:
	 *     (left=PrimaryExpression op=Op right=Expression)
	 */
	protected void sequence_Binexpr(ISerializationContext context, Binexpr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.BINEXPR__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.BINEXPR__LEFT));
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.BINEXPR__OP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.BINEXPR__OP));
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.BINEXPR__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.BINEXPR__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBinexprAccess().getLeftPrimaryExpressionParserRuleCall_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getBinexprAccess().getOpOpParserRuleCall_2_0(), semanticObject.getOp());
		feeder.accept(grammarAccess.getBinexprAccess().getRightExpressionParserRuleCall_3_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Colprod returns Colprod
	 *
	 * Constraint:
	 *     colIndex=Expression
	 */
	protected void sequence_Colprod(ISerializationContext context, Colprod semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.COLPROD__COL_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.COLPROD__COL_INDEX));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getColprodAccess().getColIndexExpressionParserRuleCall_1_0(), semanticObject.getColIndex());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Colsum returns Colsum
	 *
	 * Constraint:
	 *     colIndex=Expression
	 */
	protected void sequence_Colsum(ISerializationContext context, Colsum semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.COLSUM__COL_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.COLSUM__COL_INDEX));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getColsumAccess().getColIndexExpressionParserRuleCall_1_0(), semanticObject.getColIndex());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Export
	 *     Export returns Export
	 *
	 * Constraint:
	 *     url=STRING
	 */
	protected void sequence_Export(ISerializationContext context, Export semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.EXPORT__URL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.EXPORT__URL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExportAccess().getUrlSTRINGTerminalRuleCall_1_0(), semanticObject.getUrl());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Expression returns Expression
	 *
	 * Constraint:
	 *     (value=PrimaryExpression | value=Binexpr)
	 */
	protected void sequence_Expression(ISerializationContext context, Expression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns InsertCol
	 *     InsertCol returns InsertCol
	 *
	 * Constraint:
	 *     (colIndex=Expression colName=STRING)
	 */
	protected void sequence_InsertCol(ISerializationContext context, InsertCol semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.INSERT_COL__COL_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.INSERT_COL__COL_INDEX));
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.INSERT_COL__COL_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.INSERT_COL__COL_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInsertColAccess().getColIndexExpressionParserRuleCall_1_0(), semanticObject.getColIndex());
		feeder.accept(grammarAccess.getInsertColAccess().getColNameSTRINGTerminalRuleCall_3_0(), semanticObject.getColName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns InsertLine
	 *     InsertLine returns InsertLine
	 *
	 * Constraint:
	 *     lineIndex=Expression
	 */
	protected void sequence_InsertLine(ISerializationContext context, InsertLine semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.INSERT_LINE__LINE_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.INSERT_LINE__LINE_INDEX));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInsertLineAccess().getLineIndexExpressionParserRuleCall_1_0(), semanticObject.getLineIndex());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     IntValue returns IntValue
	 *
	 * Constraint:
	 *     value=INT
	 */
	protected void sequence_IntValue(ISerializationContext context, IntValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.INT_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.INT_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntValueAccess().getValueINTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Lineprod returns Lineprod
	 *
	 * Constraint:
	 *     lineIndex=Expression
	 */
	protected void sequence_Lineprod(ISerializationContext context, Lineprod semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.LINEPROD__LINE_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.LINEPROD__LINE_INDEX));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLineprodAccess().getLineIndexExpressionParserRuleCall_1_0(), semanticObject.getLineIndex());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Linesum returns Linesum
	 *
	 * Constraint:
	 *     lineIndex=Expression
	 */
	protected void sequence_Linesum(ISerializationContext context, Linesum semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.LINESUM__LINE_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.LINESUM__LINE_INDEX));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLinesumAccess().getLineIndexExpressionParserRuleCall_1_0(), semanticObject.getLineIndex());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Loadscope returns Loadscope
	 *
	 * Constraint:
	 *     ((url=STRING instructions+=Instruction*) | instructions+=Instruction+)
	 */
	protected void sequence_Loadscope(ISerializationContext context, Loadscope semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Modify
	 *     Modify returns Modify
	 *
	 * Constraint:
	 *     (colIndex=Expression rowIndex=Expression (value=Expression | value=StringValue))
	 */
	protected void sequence_Modify(ISerializationContext context, Modify semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     PrimaryExpression returns PrimaryExpression
	 *
	 * Constraint:
	 *     (
	 *         value=IntValue | 
	 *         value=Selectcell | 
	 *         value=Linesum | 
	 *         value=Colsum | 
	 *         value=Lineprod | 
	 *         value=Colprod
	 *     )
	 */
	protected void sequence_PrimaryExpression(ISerializationContext context, PrimaryExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Print
	 *     Print returns Print
	 *
	 * Constraint:
	 *     (value=Expression | value=StringValue)
	 */
	protected void sequence_Print(ISerializationContext context, Print semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Programme returns Programme
	 *
	 * Constraint:
	 *     loadscopes+=Loadscope+
	 */
	protected void sequence_Programme(ISerializationContext context, Programme semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns RemoveCol
	 *     RemoveCol returns RemoveCol
	 *
	 * Constraint:
	 *     colIndex=Expression
	 */
	protected void sequence_RemoveCol(ISerializationContext context, RemoveCol semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.REMOVE_COL__COL_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.REMOVE_COL__COL_INDEX));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRemoveColAccess().getColIndexExpressionParserRuleCall_1_0(), semanticObject.getColIndex());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns RemoveLine
	 *     RemoveLine returns RemoveLine
	 *
	 * Constraint:
	 *     lineIndex=Expression
	 */
	protected void sequence_RemoveLine(ISerializationContext context, RemoveLine semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.REMOVE_LINE__LINE_INDEX) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.REMOVE_LINE__LINE_INDEX));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRemoveLineAccess().getLineIndexExpressionParserRuleCall_1_0(), semanticObject.getLineIndex());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Selectcell returns Selectcell
	 *
	 * Constraint:
	 *     (cellX=Expression cellY=Expression)
	 */
	protected void sequence_Selectcell(ISerializationContext context, Selectcell semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.SELECTCELL__CELL_X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.SELECTCELL__CELL_X));
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.SELECTCELL__CELL_Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.SELECTCELL__CELL_Y));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSelectcellAccess().getCellXExpressionParserRuleCall_1_0(), semanticObject.getCellX());
		feeder.accept(grammarAccess.getSelectcellAccess().getCellYExpressionParserRuleCall_3_0(), semanticObject.getCellY());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Instruction returns Store
	 *     Store returns Store
	 *
	 * Constraint:
	 *     url=STRING
	 */
	protected void sequence_Store(ISerializationContext context, Store semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.STORE__URL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.STORE__URL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStoreAccess().getUrlSTRINGTerminalRuleCall_1_0(), semanticObject.getUrl());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     StringValue returns StringValue
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_StringValue(ISerializationContext context, StringValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, IdmdslPackage.Literals.STRING_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, IdmdslPackage.Literals.STRING_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringValueAccess().getValueSTRINGTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
}
