/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import idm.project.ui.internal.ProjectActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ProjectActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ProjectActivator activator = ProjectActivator.getInstance();
		return activator != null ? activator.getInjector(ProjectActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
