/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.idmdsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.idmdsl.IdmdslPackage;
import org.xtext.example.mydsl.idmdsl.MathExpression;
import org.xtext.example.mydsl.idmdsl.Selectcell;
import org.xtext.example.mydsl.idmdsl.StringValue;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Selectcell</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl#getLineIndex <em>Line Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.idmdsl.impl.SelectcellImpl#getColName <em>Col Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SelectcellImpl extends MathPrimaryExpressionImpl implements Selectcell
{
  /**
   * The cached value of the '{@link #getLineIndex() <em>Line Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLineIndex()
   * @generated
   * @ordered
   */
  protected MathExpression lineIndex;

  /**
   * The cached value of the '{@link #getColName() <em>Col Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColName()
   * @generated
   * @ordered
   */
  protected StringValue colName;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SelectcellImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IdmdslPackage.Literals.SELECTCELL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MathExpression getLineIndex()
  {
    return lineIndex;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLineIndex(MathExpression newLineIndex, NotificationChain msgs)
  {
    MathExpression oldLineIndex = lineIndex;
    lineIndex = newLineIndex;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IdmdslPackage.SELECTCELL__LINE_INDEX, oldLineIndex, newLineIndex);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLineIndex(MathExpression newLineIndex)
  {
    if (newLineIndex != lineIndex)
    {
      NotificationChain msgs = null;
      if (lineIndex != null)
        msgs = ((InternalEObject)lineIndex).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IdmdslPackage.SELECTCELL__LINE_INDEX, null, msgs);
      if (newLineIndex != null)
        msgs = ((InternalEObject)newLineIndex).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IdmdslPackage.SELECTCELL__LINE_INDEX, null, msgs);
      msgs = basicSetLineIndex(newLineIndex, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdmdslPackage.SELECTCELL__LINE_INDEX, newLineIndex, newLineIndex));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringValue getColName()
  {
    return colName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetColName(StringValue newColName, NotificationChain msgs)
  {
    StringValue oldColName = colName;
    colName = newColName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IdmdslPackage.SELECTCELL__COL_NAME, oldColName, newColName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColName(StringValue newColName)
  {
    if (newColName != colName)
    {
      NotificationChain msgs = null;
      if (colName != null)
        msgs = ((InternalEObject)colName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IdmdslPackage.SELECTCELL__COL_NAME, null, msgs);
      if (newColName != null)
        msgs = ((InternalEObject)newColName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IdmdslPackage.SELECTCELL__COL_NAME, null, msgs);
      msgs = basicSetColName(newColName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdmdslPackage.SELECTCELL__COL_NAME, newColName, newColName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IdmdslPackage.SELECTCELL__LINE_INDEX:
        return basicSetLineIndex(null, msgs);
      case IdmdslPackage.SELECTCELL__COL_NAME:
        return basicSetColName(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IdmdslPackage.SELECTCELL__LINE_INDEX:
        return getLineIndex();
      case IdmdslPackage.SELECTCELL__COL_NAME:
        return getColName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IdmdslPackage.SELECTCELL__LINE_INDEX:
        setLineIndex((MathExpression)newValue);
        return;
      case IdmdslPackage.SELECTCELL__COL_NAME:
        setColName((StringValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IdmdslPackage.SELECTCELL__LINE_INDEX:
        setLineIndex((MathExpression)null);
        return;
      case IdmdslPackage.SELECTCELL__COL_NAME:
        setColName((StringValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IdmdslPackage.SELECTCELL__LINE_INDEX:
        return lineIndex != null;
      case IdmdslPackage.SELECTCELL__COL_NAME:
        return colName != null;
    }
    return super.eIsSet(featureID);
  }

} //SelectcellImpl
