/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import idm.project.ui.internal.ProjectActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProjectActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
